N: 10       # максимальноу число повторных логинов    в минуту
M: 100      # максимальноу число повторных паролей    в минуту
K: 1000     # максимальноу число повторных ip Адресов в минуту
Port: ":8080"  # порт сервера
LogPath: "BruteforceConfig.log" # Путь к файлу логов